/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx,css}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: { DEFAULT: 'var(--primary)', foreground: 'var(--primary-foreground)' },
        secondary: { DEFAULT: 'var(--secondary)', foreground: 'var(--secondary-foreground)' },
        destructive: { DEFAULT: 'var(--destructive)', foreground: 'var(--destructive-foreground)' },
        muted: { DEFAULT: 'var(--muted)', foreground: 'var(--muted-foreground)' },
        accent: { DEFAULT: 'var(--accent)', foreground: 'var(--accent-foreground)' },
        popover: { DEFAULT: 'var(--popover)', foreground: 'var(--popover-foreground)' },
        card: { DEFAULT: 'var(--card)', foreground: 'var(--card-foreground)' },
      },
      fontFamily: {
        sans: ['Space Grotesk', 'Inter', 'sans-serif'],
        display: ['Syne', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        xl: '1rem',
        card: '1.25rem',
        pill: '9999px',
        'lotto-ball': '50%',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
  safelist: [
    'text-success-500',
    'text-error-500',
    'text-warning-500',
    'text-info-500',
    'bg-success-50',
    'bg-error-50',
    'bg-warning-50',
    'bg-info-50',
    'animate-fade-in',
    'animate-slide-up',
    'animate-pulse',
    'animate-float',
    'animate-pulse-glow',
    'animate-3d-bounce',
    'animate-appear',
    'animate-float-ball',
    'animate-pulse-glow-cosmic',
    'animate-pulse-glow-electric',
    'animate-pulse-glow-neon',
    'animate-rotate-3d',
    'animate-appear-ball',
    'perspective-500',
    'perspective-1000',
    'perspective-1500',
    'perspective-2000',
    'transform-style-preserve-3d',
    'backface-visibility-hidden',
    'sr-only',
    'focus-visible:ring-2',
    'focus-visible:ring-primary-500',
    'shadow-lotto-ball',
    'shadow-lotto-ball-hover',
    'shadow-glow-cosmic',
    'shadow-glow-electric',
    'shadow-glow-neon',
    'text-red-500',
  ],
}